SecRule REQUEST_URI "@contains hello" "id:10, phase:1, nolog, pass, t:none, setvar:tx.trivial=false"
SecRule REQUEST_URI "@contains chau" "id:11, phase:1, nolog, pass, t:none, setvar:tx.trivial2=false"
