#WACE configuration file

# WACE general configuration
#The full path to the wace log file
logpath: "/dev/stdout"
#The level of debug, the valid options are - ERRO, WARN, INFO, DEBUG
loglevel: "DEBUG"

#The model plugins configuration
modelplugins:
  - id: "trivial"
    plugintype: RequestHeaders
    path: "wace_waf/testdata/plugins/trivial.so"
    mode: sync
  - id: "trivial2"
    plugintype: RequestBody
    path: "wace_waf/testdata/plugins/trivial2.so"
    mode: sync
    
decisionplugins:
  - id: "weighted_sum"
    path: "wace_waf/testdata/plugins/weighted_sum.so"
    model_weights:
      trivial: 0.25
      trivial2: 0.25
    waf_weight: 0.5
    params:
      threshold: "0.5"
  - id: "weighted_sum_training"
    path: "wace_waf/testdata/plugins/weighted_sum_training.so"
    model_weights:
      trivial: 0.25
      trivial2: 0.25
    waf_weight: 0.5
    params:
      threshold: "0.5"
    training: true
    training_data:
      max_samples: 10
      result_file_path: "/tmp/training_results.ndjson"

crs_version: "4.4.0-dev"
early_blocking: false
blocking: false

exception_ids:
  RequestHeaders: 100
  RequestBody: 200
  AllRequest: 300
  ResponseHeaders: 400
  ResponseBody: 500
  AllResponse: 600
